carcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,  name = 'home'),
    path('about/', views.about,  name = 'about'),
    path('cars/', views.cars_index,  name = 'index'),
    path('cars/<int:car_id>/', views.cars_detail, name = 'detail'),
    path('cars/create/', views.CarCreate.as_view(), name = 'cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name = 'cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name = 'cars_delete'),
    path('cars/<int:car_id>/add_mod/', views.add_mod, name = 'add_mod'),
    path('cars/<int:car_id>/assoc_track/<int:track_id>/', views.assoc_track, name = 'assoc_track'),
    path('cars/<int:car_id>/unassoc_track/<int:track_id>/', views.unassoc_track, name = 'unassoc_track'),
    path('tracks/', views.TrackList.as_view(), name='tracks_index'),
    path('tracks/<int:pk>/', views.TrackDetail.as_view(), name='tracks_detail'),
    path('tracks/create/', views.TrackCreate.as_view(), name='tracks_create'),
    path('tracks/<int:pk>/update/', views.TrackUpdate.as_view(), name='tracks_update'),
    path('tracks/<int:pk>/delete/', views.TrackDelete.as_view(), name='tracks_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

USES = (
    ('P', 'Performance'),
    ('A', 'Aesthetic'),
    ('S', 'Saftey'),
    ('PA', 'Performance & Aesthetic'),
    ('PS', 'Performance & Saftey'),
    ('SA', 'Saftey & Aesthetic'),
    ('A', 'All'),
)

class Track(models.Model):
    track = models.CharField(max_length=200)
    location = models.CharField(
        max_length=500,
        default='USA'
        )

    def __str__(self):
        return self.track

    def get_absolute_url(self):
        return reverse('tracks_detail', kwargs={'pk': self.id})

class Car(models.Model):
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=200)
    year = models.IntegerField()
    description = models.TextField(max_length=250)
    tracks = models.ManyToManyField(Track)

    def __str__(self):
        return f"{self.make} {self.model} ({self.id})"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'car_id': self.id})

class Mod(models.Model):
    part = models.CharField(max_length=300)
    use = models.CharField(
        max_length=2,
        choices=USES,
        default=USES[0][0]
    )

    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f"The {self.part} is/are a {self.get_use_display()} mod"

main_app/forms.py
from django.forms import ModelForm
from .models import Mod

class ModForm(ModelForm):
    class Meta():
        model = Mod
        fields = ['part', 'use']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Car, Track
from .forms import ModForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cars_index(request):
    cars = Car.objects.all()
    return render(request, 'cars/index.html', {
        'cars': cars
    })

def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    id_list = car.tracks.all().values_list('id')
    tracks_car_doesnt_have = Track.objects.exclude(id__in=id_list)
    mod_form = ModForm()
    return render(request, 'cars/detail.html', {
        'car': car,
        'mod_form': mod_form,
        'tracks': tracks_car_doesnt_have
    })

class CarCreate(CreateView):
    model = Car
    fields = ['make', 'model', 'year', 'description']

class CarUpdate(UpdateView):
    model = Car
    fields = '__all__'

class CarDelete(DeleteView):
    model = Car
    success_url = '/cars'

def add_mod(request, car_id):
    form = ModForm(request.POST)
    if form.is_valid():
        new_mod = form.save(commit=False)
        new_mod.car_id = car_id
        new_mod.save()
    return redirect('detail', car_id=car_id)

class TrackList(ListView):
  model = Track

class TrackDetail(DetailView):
  model = Track

class TrackCreate(CreateView):
    model = Track
    fields = '__all__'

class TrackUpdate(UpdateView):
    model = Track
    fields = ['track', 'location']

class TrackDelete(DeleteView):
    model = Track
    success_url = '/tracks'

def assoc_track(request, car_id, track_id):
    Car.objects.get(id=car_id).tracks.add(track_id)
    return redirect('detail', car_id=car_id)

def unassoc_track(request, car_id, track_id):
    Car.objects.get(id=car_id).tracks.remove(track_id)
    return redirect('detail', car_id=car_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>
<p>
    Car Collector is a an application where anyone can come and post
    cars in their garage!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav">
        <ul>
          <li><a href="/" class="brand-logo"><img id="logo-img" src="../../../static/images/Car_Collector__1_-removebg-preview.png" width="100vmin">Car Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}" id="about">About</a></li>
          <li><a href="{% url 'cars_create' %}" id="add-car">Add a Car</a></li>
          <li><a href="{% url 'index' %}" id="garage">Gallery</a></li>
          <li><a href="{% url 'tracks_create' %}">Add a Track</a></li>
          <li><a href="{% url 'tracks_index' %}">View All Tracks</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="main">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div>All Rights Reserved, © 2022 Car Collector</div>
  </footer>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class='title'>Car Details</h1>

<div class="car-contents">
  <h4 class="car-content">Make: {{ car.make }}</h4>
  <h4 class="car-content">Model: {{ car.model }}</h4>
  <h4 class="car-content">Year: {{ car.year }}</h4>
  <h4 class="car-content">Description: <br><br> {{ car.description }}</h4>
  <div class="car-action">
    <a href="{% url 'cars_update' car.id %}">Edit</a>
    <a href="{% url 'cars_delete' car.id %}">Delete</a>
  </div>
  <div class="col s6">
    <form action="{% url 'add_mod' car.id %}" method="POST">
      {% csrf_token %}
      {{ mod_form.as_p }}
      <input type="submit" class="btn" value="Add Mod">
    </form>
    <table class="striped">
      <h1>Mods:</h1>
      <thead>
        <tr><th>Part</th><th>Use</th></tr>
      </thead>
      <tbody>
        {% for mod in car.mod_set.all %}
          <tr>
            <td>{{mod.part}}</td>
            <td>{{mod.get_use_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <hr>
<div class="row">
  <div class="col s6">
    <h3>Tracks Visited</h3>
    {% if car.tracks.count %}
      {% for track in car.tracks.all %}
        <div class="card">
          <div class="card-content">
            <span id="black" class="card-title">
              The {{ track.track }} located at {{ track.location }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_track' car.id track.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>This car has never went to a track.</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Tracks</h3>
    {% if tracks.count %}
      {% for track in tracks.all %}
        <div class="card">
          <div class="card-content">
            <span id="black" class="card-title">
              The {{ track.track }} located at {{ track.location }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_track' car.id track.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No More Available Tracks.</h5>
    {% endif %}
      </div>
</div>

<script>
  const selectEl = document.getElementById('id_use');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class='title'>List of Cars</h1>

{% for car in cars %}
<div class="car">
    <div class="car-contents">
        <a href="{% url 'detail' car.id %}" id="car-content-a">
            <p class="car-content">Make: {{ car.make }}</p>
            <p class="car-content">Model: {{ car.model }}</p>
            <p class="car-content">Year: {{ car.year }}</p>
        </a>
    </div>
 </div>
{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home Page</h1>

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span>{{ object.make }} {{ object.model }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}
{% block content %}

<h1>Add Your Car</h1>

<form action="" method="POST">
    {% csrf_token %}
    <!-- for security purposes ^^^ -->
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit Your Car!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/track_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Track</h1>

  <h4>Are you sure you want to delete {{ object.track }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'tracks_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/track_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Track Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span id="black" class="card-title">{{ track.track }}</span>
        <p id="black">Location: {{ track.location }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'tracks_update' track.id %}">Edit</a>
        <a href="{% url 'tracks_delete' track.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/track_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Owner</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/track_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Track List</h1>

{% for track in track_list %}
  <a href="{% url 'tracks_detail' track.id %}">
    <div class="card">
        <div class="card-content">
            <span id="black" class="card-title">{{ track.track }}</span>
            <p id="black"> Location: {{ track.location }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}